
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.JWindow;
import static javax.xml.bind.DatatypeConverter.parseInteger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arina
 */
public class InterfataGrafica extends javax.swing.JFrame {

   public Agenda agenda = new Agenda();
   private DefaultListModel<Contact> modelLista = new DefaultListModel<Contact>();
   private DefaultComboBoxModel filtre = new DefaultComboBoxModel(new String[]{"NR_FIX", "NR_MOBIL", "NASCUTI_ZI_CURENTA", "NASCUTI_LUNA_CURENTA", "PERSONALIZAT"});
   private DefaultComboBoxModel ordonare = new DefaultComboBoxModel(new String[]{"DUPA_NUME", "DUPA_PRENUME", "DUPA_VARSTA", "DUPA_TELEFON"});
    
   ImageIcon imagine;
    String[] Imagini = {"1.jpg", "2.jpg", "3.jpg"};
    int i = 0;
    JWindow window = new JWindow();
    ActionListener task = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            if (i == 3) {
                i = 0;
            } else {

                imagine = new ImageIcon(getClass().getResource(Imagini[i]));
                poza.setIcon(imagine);
                i++;
            }

        }
    };
   
    javax.swing.Timer timer = new javax.swing.Timer(1000, task);
   public InterfataGrafica() {
       initComponents();
        cbFiltru.setModel(filtre);
        cbOrdonare.setModel(ordonare);
        bAdaugaContact.setEnabled(false);
        bStergeContact.setEnabled(false);
        bEditeazaContact.setEnabled(false);
        bFiltreaza.setEnabled(false);
        bOrdoneaza.setEnabled(false);
        cbFiltru.setEnabled(false);
        cbOrdonare.setEnabled(false);
        tfFiltru.setEnabled(false);
        mbSalvare.setEnabled(false);
        mbDeschidere.setEnabled(false);
        timer.start();
    }

   
   private void actualizareModel(List m) {
        modelLista.clear();
        for (int j = 0; j < m.size(); j++) {
            Contact c = (Contact) m.get(j);
            modelLista.addElement(c);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iesire = new javax.swing.JDialog();
        bIesireDa = new javax.swing.JButton();
        bIesireNu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        StergereContact = new javax.swing.JDialog();
        bStergereDa = new javax.swing.JButton();
        bStergereNu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Inregistrare = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        tfInregistrareParola = new javax.swing.JTextField();
        bInregistrareValideaza = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        AdaugaContact = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfn1 = new javax.swing.JTextField();
        tfp1 = new javax.swing.JTextField();
        tftel1 = new javax.swing.JTextField();
        tfd1 = new javax.swing.JTextField();
        bAdauga = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        ModificaContact = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfn = new javax.swing.JTextField();
        tfp = new javax.swing.JTextField();
        tftel = new javax.swing.JTextField();
        tfd = new javax.swing.JTextField();
        bModifica = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cbFiltru = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfFiltru = new javax.swing.JTextField();
        bFiltreaza = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbOrdonare = new javax.swing.JComboBox<>();
        bOrdoneaza = new javax.swing.JButton();
        bAdaugaContact = new javax.swing.JButton();
        bEditeazaContact = new javax.swing.JButton();
        bStergeContact = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlAgenda = new javax.swing.JList<>();
        poza = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbFisiere = new javax.swing.JMenu();
        mbDeschidere = new javax.swing.JMenuItem();
        mbSalvare = new javax.swing.JMenuItem();
        mbIesire = new javax.swing.JMenuItem();
        mbAjutor = new javax.swing.JMenu();
        mbInregistrare = new javax.swing.JMenuItem();
        mbDespre = new javax.swing.JMenuItem();

        bIesireDa.setText("Da");
        bIesireDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIesireDaActionPerformed(evt);
            }
        });

        bIesireNu.setText("Nu");
        bIesireNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIesireNuActionPerformed(evt);
            }
        });

        jLabel4.setText("Doriti sa parasiti aplicatia?");

        javax.swing.GroupLayout IesireLayout = new javax.swing.GroupLayout(Iesire.getContentPane());
        Iesire.getContentPane().setLayout(IesireLayout);
        IesireLayout.setHorizontalGroup(
            IesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IesireLayout.createSequentialGroup()
                .addGroup(IesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IesireLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(IesireLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bIesireDa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bIesireNu)))
                .addContainerGap())
        );
        IesireLayout.setVerticalGroup(
            IesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IesireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIesireDa)
                    .addComponent(bIesireNu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bStergereDa.setText("Da");
        bStergereDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStergereDaActionPerformed(evt);
            }
        });

        bStergereNu.setText("Nu");
        bStergereNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStergereNuActionPerformed(evt);
            }
        });

        jLabel5.setText("Doriti sa stergeti contactul selectat?");

        javax.swing.GroupLayout StergereContactLayout = new javax.swing.GroupLayout(StergereContact.getContentPane());
        StergereContact.getContentPane().setLayout(StergereContactLayout);
        StergereContactLayout.setHorizontalGroup(
            StergereContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StergereContactLayout.createSequentialGroup()
                .addGroup(StergereContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StergereContactLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(StergereContactLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bStergereDa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bStergereNu)))
                .addContainerGap())
        );
        StergereContactLayout.setVerticalGroup(
            StergereContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StergereContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StergereContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bStergereDa)
                    .addComponent(bStergereNu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Introduceti codul de inregistrare");

        bInregistrareValideaza.setText("Valideaza");
        bInregistrareValideaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInregistrareValideazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InregistrareLayout = new javax.swing.GroupLayout(Inregistrare.getContentPane());
        Inregistrare.getContentPane().setLayout(InregistrareLayout);
        InregistrareLayout.setHorizontalGroup(
            InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InregistrareLayout.createSequentialGroup()
                .addGroup(InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InregistrareLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfInregistrareParola)))
                    .addGroup(InregistrareLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(bInregistrareValideaza)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        InregistrareLayout.setVerticalGroup(
            InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InregistrareLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfInregistrareParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(bInregistrareValideaza)
                .addContainerGap())
        );

        jLabel11.setText("Nume:");

        jLabel12.setText("Prenume:");

        jLabel13.setText("Telefon:");

        jLabel14.setText("Data nasterii:");

        bAdauga.setText("Adauga contact");
        bAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdaugaContactLayout = new javax.swing.GroupLayout(AdaugaContact.getContentPane());
        AdaugaContact.getContentPane().setLayout(AdaugaContactLayout);
        AdaugaContactLayout.setHorizontalGroup(
            AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdaugaContactLayout.createSequentialGroup()
                .addGroup(AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdaugaContactLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfn1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfp1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfd1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AdaugaContactLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(bAdauga, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        AdaugaContactLayout.setVerticalGroup(
            AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdaugaContactLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tftel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdaugaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(31, 31, 31)
                .addComponent(bAdauga)
                .addContainerGap())
        );

        jLabel15.setText("Nume:");

        jLabel16.setText("Prenume:");

        jLabel17.setText("Telefon:");

        jLabel18.setText("Data nasterii:");

        bModifica.setText("Modifica contact");
        bModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Fix");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Mobil");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificaContactLayout = new javax.swing.GroupLayout(ModificaContact.getContentPane());
        ModificaContact.getContentPane().setLayout(ModificaContactLayout);
        ModificaContactLayout.setHorizontalGroup(
            ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificaContactLayout.createSequentialGroup()
                .addGroup(ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificaContactLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfd, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ModificaContactLayout.createSequentialGroup()
                                .addComponent(tftel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton4))))
                    .addGroup(ModificaContactLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(bModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModificaContactLayout.setVerticalGroup(
            ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificaContactLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tftel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addGroup(ModificaContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(31, 31, 31)
                .addComponent(bModifica)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Filtrare");

        cbFiltru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "numar fix", "numar de mobil", "nascuti astazi", "nascuti in luna curenta", "personalizat" }));
        cbFiltru.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbFiltru.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cbFiltruComponentShown(evt);
            }
        });
        cbFiltru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltruActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtru");

        bFiltreaza.setText("Filtreaza");

        jLabel3.setText("Ordonare");

        cbOrdonare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dupa nume", "dupa prenume", "dupa data nasterii", "dupa telefon" }));

        bOrdoneaza.setText("Ordoneaza");

        bAdaugaContact.setText("Adauga contact");
        bAdaugaContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugaContactActionPerformed(evt);
            }
        });

        bEditeazaContact.setText("Editeaza contact selectat");
        bEditeazaContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditeazaContactActionPerformed(evt);
            }
        });

        bStergeContact.setText("Sterge contact selectat");
        bStergeContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStergeContactActionPerformed(evt);
            }
        });

        jlAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jlAgenda);

        mbFisiere.setText("Fisiere");

        mbDeschidere.setText("Deschidere");
        mbDeschidere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbDeschidereActionPerformed(evt);
            }
        });
        mbFisiere.add(mbDeschidere);

        mbSalvare.setText("Salvare");
        mbFisiere.add(mbSalvare);

        mbIesire.setText("Iesire");
        mbIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbIesireActionPerformed(evt);
            }
        });
        mbFisiere.add(mbIesire);

        jMenuBar1.add(mbFisiere);

        mbAjutor.setText("Ajutor");

        mbInregistrare.setText("Inregistrare");
        mbInregistrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbInregistrareActionPerformed(evt);
            }
        });
        mbAjutor.add(mbInregistrare);

        mbDespre.setText("Despre");
        mbDespre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbDespreActionPerformed(evt);
            }
        });
        mbAjutor.add(mbDespre);

        jMenuBar1.add(mbAjutor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbOrdonare, 0, 252, Short.MAX_VALUE)
                                    .addComponent(cbFiltru, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bOrdoneaza, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfFiltru, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bFiltreaza, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bAdaugaContact, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(bStergeContact, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(bEditeazaContact, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbFiltru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfFiltru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltreaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbOrdonare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOrdoneaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAdaugaContact)
                    .addComponent(bEditeazaContact)
                    .addComponent(bStergeContact))
                .addGap(27, 27, 27)
                .addComponent(poza, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbDeschidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbDeschidereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbDeschidereActionPerformed

    private void mbInregistrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbInregistrareActionPerformed
        Inregistrare.setVisible(true);
        Inregistrare.pack();
    }//GEN-LAST:event_mbInregistrareActionPerformed

    private void cbFiltruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFiltruActionPerformed

    private void cbFiltruComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbFiltruComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFiltruComponentShown

    private void mbIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbIesireActionPerformed
       Iesire.setModal(true);
       Iesire.setVisible(true);
       Iesire.pack();
    }//GEN-LAST:event_mbIesireActionPerformed

    private void bIesireDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIesireDaActionPerformed
       System.exit(0);
    }//GEN-LAST:event_bIesireDaActionPerformed

    private void bIesireNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIesireNuActionPerformed
       Iesire.setVisible(false);
       Iesire.pack();
    }//GEN-LAST:event_bIesireNuActionPerformed

    private void bStergeContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStergeContactActionPerformed
        StergereContact.setModal(true);
        StergereContact.setVisible(true);
        StergereContact.pack();
    }//GEN-LAST:event_bStergeContactActionPerformed

    private void bStergereDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStergereDaActionPerformed
        if (jlAgenda.getSelectedIndex() != -1) {
            modelLista.remove(jlAgenda.getSelectedIndex());
            agenda.Stergere((Contact) agenda.Contacte.get(jlAgenda.getSelectedIndex()));
            StergereContact.setVisible(false);
        }
    }//GEN-LAST:event_bStergereDaActionPerformed

    private void bStergereNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStergereNuActionPerformed
       StergereContact.setVisible(false);
       StergereContact.pack();
    }//GEN-LAST:event_bStergereNuActionPerformed

    private void mbDespreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbDespreActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Proiect realizat de Scăunașu Arina Mihaela în septembrie 2018." + "\n"  + "Pentru inregistrare folositi codul: 000000.");
    }//GEN-LAST:event_mbDespreActionPerformed

    private void bInregistrareValideazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInregistrareValideazaActionPerformed
        if(tfInregistrareParola.getText().equals("000000")){
            bAdaugaContact.setEnabled(true);
            bStergeContact.setEnabled(true);
            bEditeazaContact.setEnabled(true);
            bFiltreaza.setEnabled(true);
            bOrdoneaza.setEnabled(true);
            cbFiltru.setEnabled(true);
            cbOrdonare.setEnabled(true);
            tfFiltru.setEnabled(true);
            mbSalvare.setEnabled(true);
            mbDeschidere.setEnabled(true);
            Inregistrare.setVisible(false);
            mbInregistrare.setEnabled(false);
            //timer.stop();
           // poza.setVisible(false);
        }
        
        else {
            JOptionPane.showMessageDialog(rootPane, "Parola incorecta!");
        }
    }//GEN-LAST:event_bInregistrareValideazaActionPerformed

    private void bAdaugaContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugaContactActionPerformed
        AdaugaContact.setModal(true);
        AdaugaContact.pack();
        AdaugaContact.setVisible(true);
    }//GEN-LAST:event_bAdaugaContactActionPerformed

    private void bEditeazaContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditeazaContactActionPerformed
        ModificaContact.setModal(true);
        ModificaContact.setVisible(true);
        ModificaContact.pack();
    }//GEN-LAST:event_bEditeazaContactActionPerformed

    private void bAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugaActionPerformed
        try{
            agenda.Adauga(tfn1.getText(), tfp1.getText(), tfd1.getText(), tftel1.getText());
            jlAgenda.setModel(modelLista);
            actualizareModel(agenda.Contacte);          
            AdaugaContact.setVisible(false);
            
        } /*catch(NullPointerException n){
             JOptionPane.showMessageDialog(this, "Eroare");
          } */
        
          /*catch(IllegalArgumentException n){
             JOptionPane.showMessageDialog(this, "Eroare");
          } */
          
         /*catch(DateTimeParseException d){
              JOptionPane.showMessageDialog(this, "Problema parsare data");
          }*/
        
         /*catch(UnsupportedOperationException u){
              JOptionPane.showMessageDialog(this, "Operatie de adaugare invalida!");
         }
        */
          /*catch(ClassCastException cc){
              JOptionPane.showMessageDialog(this, "ClasscastException!");
          }*/
        
          catch (RuntimeException e) {
             if (e.getMessage().equals("Contactul exista in lista deja!")) {
                JOptionPane.showMessageDialog(this, "Contactul exista in lista de cotacte deja!");
            }
             if (e.getMessage().equals("Nume prea scurt!")) {
                JOptionPane.showMessageDialog(this, "Nume prea scurt!");
            }
            
            if (e.getMessage().equals("Prenume prea scurt!")) {
                JOptionPane.showMessageDialog(this, "Prenume prea scurt!");
            }
           
            /*if (e.getMessage().contains("parse")) {
                JOptionPane.showMessageDialog(this, "PROBLEMA LA FORMATUL DATEI zz/ll/yyyy!");
            }*/
            if (e.getMessage().equals("Numarul NU incepe cu 07,02 sau 03!")) {
                JOptionPane.showMessageDialog(this, "Numarul NU incepe cu 07,02 sau 03!");
            }
            
            if (e.getMessage().equals("An invalid!")) {
                JOptionPane.showMessageDialog(this, "An invalid! Anul trebuie sa fie intre 1920 si anul curent!");
            }
            
                        
            if (e.getMessage().equals("Numarul de mobil nu are 10 cifre!")) {
                JOptionPane.showMessageDialog(this, "Numarul de mobil nu are 10 cifre!");
            }
          
            if (e.getMessage().equals("Numarul nu este intr-o retea existenta in Romania!")) {
                JOptionPane.showMessageDialog(this, "Numarul nu este intr-o retea existenta in Romania!");
            }
            
           if (e.getMessage().equals("Numarul de fix nu are 10 cifre!")) {
                JOptionPane.showMessageDialog(this, "Numarul de fix nu are 10 cifre!");
            }
            
           
        }
    }//GEN-LAST:event_bAdaugaActionPerformed

    private void bModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaActionPerformed
        try{
            agenda.ModificaContact((Contact) jlAgenda.getSelectedValue(), tfn.getText(), tfp.getText(), tfd.getText(), tftel.getText());
            ModificaContact.setVisible(false);
        } catch(RuntimeException e) {
            if(e.getMessage().equals("Numarul nu incepe cu 07, 03 sau 02!")){ 
                  JOptionPane.showMessageDialog(this, "Numarul nu incepe cu 07, 03 sau 02!");  
            }
            
            if(e.getMessage().equals("Numarul nu are 10 cifre!")){ 
                  JOptionPane.showMessageDialog(this, "Numarul nu are 10 cifre!");  
            }
            
            if(e.getMessage().equals("An invalid!")){ 
                  JOptionPane.showMessageDialog(this, "An invalid! Anul trebuie sa fie mai mare decat 1920 si NU POATE FI MAI MARE DECAT ANUL CURENT!");  
            }
            
            if(e.getMessage().equals("Prenume prea scurt!")){ 
                  JOptionPane.showMessageDialog(this, "Prenume prea scurt!");  
            }
            
            if(e.getMessage().equals("Nume prea scurt!")){ 
                  JOptionPane.showMessageDialog(this, "Nume prea scurt!");  
            }
            
            if(e.getMessage().equals("Deja exista un contact cu aceste date!")){ 
                  JOptionPane.showMessageDialog(this, "Deja exista un contact cu aceste date!");  
            }
            
            
        }
    }//GEN-LAST:event_bModificaActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfataGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfataGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfataGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfataGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfataGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AdaugaContact;
    private javax.swing.JDialog Iesire;
    private javax.swing.JDialog Inregistrare;
    private javax.swing.JDialog ModificaContact;
    private javax.swing.JDialog StergereContact;
    private javax.swing.JButton bAdauga;
    private javax.swing.JButton bAdaugaContact;
    private javax.swing.JButton bEditeazaContact;
    private javax.swing.JButton bFiltreaza;
    private javax.swing.JButton bIesireDa;
    private javax.swing.JButton bIesireNu;
    private javax.swing.JButton bInregistrareValideaza;
    private javax.swing.JButton bModifica;
    private javax.swing.JButton bOrdoneaza;
    private javax.swing.JButton bStergeContact;
    private javax.swing.JButton bStergereDa;
    private javax.swing.JButton bStergereNu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbFiltru;
    private javax.swing.JComboBox<String> cbOrdonare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Contact> jlAgenda;
    private javax.swing.JMenu mbAjutor;
    private javax.swing.JMenuItem mbDeschidere;
    private javax.swing.JMenuItem mbDespre;
    private javax.swing.JMenu mbFisiere;
    private javax.swing.JMenuItem mbIesire;
    private javax.swing.JMenuItem mbInregistrare;
    private javax.swing.JMenuItem mbSalvare;
    private javax.swing.JLabel poza;
    private javax.swing.JTextField tfFiltru;
    private javax.swing.JTextField tfInregistrareParola;
    private javax.swing.JTextField tfd;
    private javax.swing.JTextField tfd1;
    private javax.swing.JTextField tfn;
    private javax.swing.JTextField tfn1;
    private javax.swing.JTextField tfp;
    private javax.swing.JTextField tfp1;
    private javax.swing.JTextField tftel;
    private javax.swing.JTextField tftel1;
    // End of variables declaration//GEN-END:variables
}
